### ISSUE TITLE
Error decoding non-breaking space in window title.

### ISSUE THREAD

**Issue by KenjiTakahashi** [tailhook/tilenol#15]
Traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python3.3/site-packages/tilenol/main.py", line 206, in loop
    self.dispatcher.dispatch(i)
  File "/usr/lib/python3.3/site-packages/tilenol/events.py", line 44, in dispatch
    meth(ev)
  File "/usr/lib/python3.3/site-packages/tilenol/events.py", line 234, in handle_PropertyNotifyEvent
    win.update_property(ev.atom)
  File "/usr/lib/python3.3/site-packages/tilenol/window.py", line 249, in update_property
    *self.xcore.get_property(self, atom))
  File "/usr/lib/python3.3/site-packages/tilenol/xcb/core.py", line 208, in get_property
    return typ, result['value'].decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 23: invalid start byte
```

After investigating it turned out that if window title has a non-breaking space (`\xc2\xa0`) then get_property gets a proper title, but immediately after it gets another one with... already decoded space (which turns out to be represented as `\xa0`). And it, obviously, fails to decode it again.

I doesn't seem to do any bad, though, but it pollutes my log file with lots of crap.

**Comment by Aareon** [comment]
Looks like this was resolved in https://github.com/tailhook/tilenol/commit/fb6ec4fbfcb2b468e18f53ebbafdb62af262fa35#diff-3f8204e13b56a8389176bdeebc9b4a32

**Comment by Aareon** [comment]
Looks like this was resolved in https://github.com/tailhook/tilenol/commit/fb6ec4fbfcb2b468e18f53ebbafdb62af262fa35
